//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCLUOTMUONTHEOTHELOAI
    {
        public int MaBaoCao { get; set; }
        public int MaTheLoai { get; set; }
        public Nullable<int> SoLuotMuon { get; set; }
        public Nullable<decimal> TyLe { get; set; }
    
        public virtual BCTONGLUOTMUON BCTONGLUOTMUON { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
