//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCTONGLUOTMUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCTONGLUOTMUON()
        {
            this.BCLUOTMUONTHEOTHELOAIs = new HashSet<BCLUOTMUONTHEOTHELOAI>();
        }
    
        public int id { get; set; }
        public string MaBaoCao { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<int> TongSoLuotMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCLUOTMUONTHEOTHELOAI> BCLUOTMUONTHEOTHELOAIs { get; set; }
    }
}
