//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCGIA()
        {
            this.PHIEUMUONTRAs = new HashSet<PHIEUMUONTRA>();
            this.PHIEUTHUTIENPHATs = new HashSet<PHIEUTHUTIENPHAT>();
        }
    
        public int id { get; set; }
        public string MaDG { get; set; }
        public int MaLoaiDG { get; set; }
        public string TenDG { get; set; }
        public System.DateTime NgaySinhDG { get; set; }
        public string DiaChiDG { get; set; }
        public string Email { get; set; }
        public System.DateTime NgayLapThe { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public Nullable<int> TongNo { get; set; }
        public string TenDangNhap { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual LOAIDOCGIA LOAIDOCGIA { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUONTRA> PHIEUMUONTRAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTHUTIENPHAT> PHIEUTHUTIENPHATs { get; set; }
    }
}
