//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUMUONTRA
    {
        public int id { get; set; }
        public string SoPhieu { get; set; }
        public int MaDG { get; set; }
        public int MaCuonSach { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public System.DateTime HanTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public int SoNgayMuon { get; set; }
        public Nullable<int> TienPhat { get; set; }
    
        public virtual CUONSACH CUONSACH { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
