//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public THAMSO() { }

        public int TuoiDGToiDa { get; set; }
        public int TuoiDGToiThieu { get; set; }
        public int GiaTriThe { get; set; }
        public int KhoangCachNamXB { get; set; }
        public int SoSachMuonToiDa { get; set; }
        public int SoNgayMuonToiDa { get; set; }
        public int TienPhatTre { get; set; }
        public bool ApDungQDThuPhat { get; set; }
    }
}
