//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DTO
{
    using System;
    using System.Collections.Generic;

    public partial class THELOAI
    {
        public string DisplayName => $"{TenTheLoai} ({MaTheLoai})";
        public override string ToString()
        {
            return DisplayName.ToString();
        }
    }
}
